#!/bin/bash
set -e

if [ "$1" = "purge" ]
then
    for i in /var/cache/karaage/graphs/projects \
             /var/cache/karaage/graphs/institutes \
             /var/cache/karaage/graphs/i_trends \
             /var/cache/karaage/graphs/trends
    do
        if dpkg-statoverride --list $i >/dev/null 2>&1
        then
            dpkg-statoverride --remove $i
        fi
    done

    rm -rf /var/cache/karaage/graphs/projects/*
    rm -rf /var/cache/karaage/graphs/trends/*
    rm -rf /var/cache/karaage/graphs/institutes/*
    rm -rf /var/cache/karaage/graphs/i_trends/*
fi

#DEBHELPER#
